name: Trigger Qa tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mday81/qatests
          event-type: qa-tests
          client-payload: '{ "foo" : "test-mus-bar"}'
